version: '3.3'

services:

  nodejs:
    container_name: nodejs
    build: .
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
